### ISSUE TITLE
Avro 1.7.4 no longer available use 1.7.5

### ISSUE THREAD

**Issue by macsilber** [charlesflynn/agiledata#2]
should update the script to 1.7.5 at http://apache.mirrors.hoobly.com/avro/stable/java/

```
State: - file
Name:      /home/vagrant/agiledata/software/lib/avro-1.7.4.jar
Function:  managed
    Result:    False
    Comment:   An exception occurred in this state: Traceback (most recent call last):
```

  File "/usr/lib/pymodules/python2.7/salt/state.py", line 1258, in call
    _cdata['args'], *_cdata['kwargs'])
  File "/usr/lib/pymodules/python2.7/salt/states/file.py", line 1131, in managed
    contents)
  File "/usr/lib/pymodules/python2.7/salt/modules/file.py", line 2048, in manage_file
    sfn = **salt**['cp.cache_file'](source, env)
  File "/usr/lib/pymodules/python2.7/salt/modules/cp.py", line 241, in cache_file
    result = **context**['cp.fileclient'].cache_file(path, env)
  File "/usr/lib/pymodules/python2.7/salt/fileclient.py", line 117, in cache_file
    return self.get_url(path, '', True, env)
  File "/usr/lib/pymodules/python2.7/salt/fileclient.py", line 372, in get_url
    *BaseHTTPServer.BaseHTTPRequestHandler.responses[ex.code]))
MinionError: HTTP error 404 reading http://apache.mirrors.hoobly.com/avro/stable/java/avro-1.7.4.jar: Nothing matches th
e given URI

**Comment by charlesflynn** [comment]
Updated, thanks!
