### ISSUE TITLE
CommandExecutionError: Requested python (python2.7) does not appear executable.

### ISSUE THREAD

**Issue by dgonzo** [charlesflynn/agiledata#9]
Trying to use the default vagrant up. Host machine is Ubuntu 13. Vagrant version is 1.4.3. I keep getting the following error. Any guidance appreciated.

```
[INFO    ] Running state [/home/vagrant/agiledata/venv] at time 05:51:52.648506

[INFO    ] Executing state virtualenv.manage for /home/vagrant/agiledata/venv
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/state.py", line 1371, in call
    **cdata['kwargs'])
  File "/usr/lib/pymodules/python2.7/salt/states/virtualenv_mod.py", line 166, in managed
    user=user
  File "/usr/lib/pymodules/python2.7/salt/modules/virtualenv_mod.py", line 203, in create
    'executable.'.format(python)
CommandExecutionError: Requested python (python2.7) does not appear executable.
```

**Comment by charlesflynn** [comment]
Hey there, so it's an Ubuntu 13 host with what guest OS distro/version?

**Comment by dgonzo** [comment]
Guest is ubuntu 12.04 lts amd64 current.  I found that if I remove python2.7 from one of the init.sls files and use just python (ubuntu 11 default is 2.7) I get past the error. But of course this will break cent install. 

I'm still experimenting. I still get failure on the pip installs. Not sure if I will be able to patch with a universal fix. If there is appetite I'm sure I can get to a limited 12.04 and cent 6 tested solution.

**Comment by charlesflynn** [comment]
I bet you're right, I used it with Fedora but not CentOS/RHEL. 

Lately I've been using Continuum.io's Anaconda/Miniconda since it takes the pain out of cross-distro Python versions and building Numpy/Scipy, and has built-in virtualenv management. When I have more time I'll play around with incorporating it, but pull requests gladly accepted if you beat me to it. Miniconda installers are [here](http://repo.continuum.io/miniconda/)

**Comment by dgonzo** [comment]
Anaconda is a great idea. If it's not too big a deal lets keep this open until one of us gets this. I really like the idea of a more generalized, python centered, workbench for doing data science. It will probably make sense to fork at some point when I've incorporated the other tools I use but that are not the focus of the book.    

On March 20, 2014 at 3:27:29 AM MDT, Charles Flynn notifications@github.com wrote:I bet you're right, I used it with Fedora but not CentOS/RHEL.   Lately I've been using Continuum.io's Anaconda/Miniconda since it takes the pain out of cross-distro Python versions and building Numpy/Scipy, and has built-in virtualenv management. When I have more time I'll play around with incorporating it, but pull requests gladly accepted if you beat me to it. Miniconda installers are here   —Reply to this email directly or view it on GitHub.

**Comment by charlesflynn** [comment]
Sure thing, leaving open. 

Speaking of Anaconda, I've also played around with Binstar as a cross-distro deployment tool for small non-python utils, like tmux, that are not always available in the environments I work in. It's the same basic mechanism that I'm using Salt for in this project's [data.sls](/charlesflynn/agiledata/blob/master/pillar/data.sls), but much more polished and user friendly. I have a [recipe repo](/charlesflynn/conda-recipes) if you're interested.
